# postgresql.conf for Lab 3 autograder
listen_addresses = ''
unix_socket_directories = '/tmp'
max_connections = 20
shared_buffers = 128MB
dynamic_shared_memory_type = posix
log_min_messages = info
client_min_messages = info
lc_messages = 'en_US.UTF-8'
lc_monetary = 'en_US.UTF-8'
lc_numeric  = 'en_US.UTF-8'
lc_time     = 'en_US.UTF-8'
